---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejsapp
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: "farazahmed100/newnodejs"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: default
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 3000
    
